#ifndef PACKET_IDS_H
#define PACKET_IDS_H

// Server -> Client Packets
#define STATUS_RESPONSE 0x00
#define DISCONNECT 0x00
#define SPAWN_ENTITY 0x01
#define PONG_RESPONSE 0x01
#define CLIENTBOUND_PLUGIN_MESSAGE_CONFIG 0x01
#define LOGIN_SUCCESS 0x02
#define ENTITY_ANIMATION 0x03
#define FINISH_CONFIGURATION 0x03
#define SET_COMPRESSION 0x03
#define ACKNOWLEDGE_BLOCK_CHANGE 0x05
#define REGISTRY_DATA 0x07
#define REMOVE_RESOURCE_PACK_CONFIG 0x08
#define UPDATE_TAGS 0x0D
#define CLIENTBOUND_KNOWN_PACKS 0x0E
#define SERVER_LINKS 0x10
#define COMMANDS 0x11
#define ENTITY_EVENT 0x1F
#define GAME_EVENT 0x22
#define KEEP_ALIVE_PLAY 0x26
#define WORLD_EVENT 0x28
#define LOGIN 0x2B //(1.21.3 => 0x2C)
#define UPDATE_ENTITY_POSITION 0x2E
#define UPDATE_ENTITY_POSITION_AND_ROTATION 0x2F
#define UPDATE_ENTITY_ROTATION 0x30
#define PLAYER_CHAT_MESSAGE 0x39
#define PLAYER_INFO_REMOVE 0x3D
#define PLAYER_INFO_UPDATE 0x3E
#define SYNCHRONIZE_PLAYER_POSITION 0x40
#define REMOVE_ENTITIES 0x42
#define ADD_RESOURCE_PACK_PLAY 0x46
#define SET_HEAD_ROTATION 0x48
#define SET_CENTER_CHUNK 0x54
#define SET_ENTITY_METADATA 0x58
#define SET_EQUIPMENT 0x5B
#define SYSTEM_CHAT_MESSAGE 0x6C
#define TELEPORT_ENTITY 0x70

// Client -> Server Packets
#define STATUS_REQUEST 0x00
#define ZERO_PACKET 0x00
#define CLIENT_INFORMATION 0x00
#define HANDSHAKE 0x00
#define PING_REQUEST 0x01
#define LOGIN_PLUGIN_RESPONSE 0x02
#define ACKNOWLEDGE_FINISH_CONFIGURATION 0x03
#define LOGIN_ACKNOWLEDGE 0x03
#define CHAT_COMMAND 0x04
#define CHAT_MESSAGE 0x06
#define PLAYER_SESSION 0x07
#define SERVERBOUND_KNOWN_PACKS 0x07
#define PLUGIN_MESSAGE_PLAY 0x12
#define PLAYER_POSITION 0x1A
#define PLAYER_POSITION_AND_ROTATION 0x1B
#define Player_ROTATION 0x1C
#define PLAYER_ON_GROUND 0x1D
#define PLAYER_ACTION 0x24
#define PLAYER_COMMAND 0x25
#define RESOURCE_PACK_RESPONSE_PLAY 0x2B
#define HELD_ITEM 0x2F
#define CREATIVE_MODE_SLOT 0x32
#define SWING_ARM 0x36
#define USE_ITEM_ON 0x38

#endif //PACKET_IDS_H
